apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: contactly
spec:
  replicas: 2
  strategy:                
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1           # How many EXTRA pods can be created during the update?
      maxUnavailable: 0
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      nodeSelector:
        node-role: backend
      containers:
      - name: backend
        image: mt1mngnw/contactly-backend:6ab2f47
        imagePullPolicy: Always
        ports:
        - containerPort: 80