apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: contactly
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      nodeSelector:
        node-role: backend
      containers:
      - name: backend
        image: mt1mngnw/contactly-backend:v1
        ports:
        - containerPort: 80