apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: contactly
spec:
  replicas: 2
  strategy:                
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1           # How many EXTRA pods can be created during the update?
      maxUnavailable: 0
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      nodeSelector:
        node-role: frontend
      containers:
      - name: frontend
        image: mt1mngnw/contactly-frontend:6ab2f47
        imagePullPolicy: Always
        ports:
        - containerPort: 80